<div class="hero hero--inside">
    <div class="hero__bg js-app-bg" data-bg="<?= page_config('hero_image') ?>"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">Как добраться</h1>

            <nav class="crumbs">
                <div class="crumbs__items">

                    <div class="crumbs__item">
                        <a href="/" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">
                            <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#arrorw-right"></use>
                                </svg>
                            </span>
                        </span>
                    </div>

                    <div class="crumbs__item">
                        <span href="/how-to-get" class="crumbs__current">Как добраться</span>
                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->
<div class="how-to-get">
    <div class="how-to-get__container container">
        <div class="how-to-get__content">
            <p>Заранее сообщайте нам Ваш маршрут, номера рейсов самолета и поездов, номера вагонов.</p>

            <p><strong>В случае существенной задержки рейсов, просим позвонить нам.</strong></p>

            <p>При необходимости такси, также сообщите нам. Мы организуем проверенных водителей и попросим для Вас
                скидку в цене. Сообщите Вашу фамилию и она будет написана на табличке у водителя в месте встречи.</p>

            <h2 class="h2">

                <div class="svg-icon svg-icon--car" aria-hidden="true">
                    <svg class="svg-icon__link">
                        <use xlink:href="#car"></use>
                    </svg>
                </div>

                Собственным автотранспортом
            </h2>

            <ol>
                <li><p>По трассе <strong>М-4 “Дон”</strong> до развилки перед п. Джубга (Туапсинский район).</li>
                <li>Дальше в сторону
                    Геленджика до <strong>п. Пшада</strong>, после которого будет <strong>развилка на п. Бетта</strong>.
                </li>
            </ol>
            Мы будем рады Вашему звонку, узнать, что Вы выехали и об ориентировочном времени прибытия. Если Вы едете в
            Бетту впервые, найти нас по приезду поможет схема (смотрите ниже).</p>

            <h2 class="h2">

                <div class="svg-icon svg-icon--airplane" aria-hidden="true">
                    <svg class="svg-icon__link">
                        <use xlink:href="#airplane"></use>
                    </svg>
                </div>

                Самолетом
            </h2>


            <ul>
                <li><p>Ближайший аэропорт – <strong>Геленджик (GDZ)</strong>, в 50 км от Бетты.<br>Сообщите нам номер
                        рейса и мы встретим Вас в аэропорту и бесплатно доставим в гостиницу Люкс.</p></li>
                <li><p>Аэропорт <strong>Краснодара</strong> находится в 160 км от Бетты, и это расстояние придется ехать
                        на такси.</p></li>
            </ul>


            <h2 class="h2">

                <div class="svg-icon svg-icon--train" aria-hidden="true">
                    <svg class="svg-icon__link">
                        <use xlink:href="#train"></use>
                    </svg>
                </div>

                Поездом
            </h2>

            <p>Ближайшие ж/д станции к Бетте – <strong>Новороссийск или Горячий Ключ</strong>. Дальше в Бетту на такси
                (90 км от обеих станций). <br>Из <strong>Новороссийска</strong> можно добраться в Бетту автобусами,
                одним
                прямым, или с пересадкой в Геленджике.</p>

            <p>Поездом можно также доехать до <strong>Краснодара</strong>. На привокзальной площади в Краснодаре
                находится также автостанция, Летом с нее, как правило, организованы 3-4 прямых рейса в Бетту.</p>

            <p>При отсутствии прямых рейсов можно доехать до а/c Пшада, в 16 км от Бетты. В Пшаде мы Вас встретим.
                Расстояние – 165 км.</p>
        </div>
    </div>
</div><!-- how-to-get -->
<div class="sheme">
    <div class="sheme__container container">
        <div class="sheme__content">
            <div class="sheme__header">Схема проезда</div>

            <div class="sheme__tabs js-tabs">
                <div class="sheme__tabs-titles" hidden><!-- FIXME Return the scheme of the way to Betta-->
                    <div class="sheme__tabs-title">
                        <button type="button" data-tab-index="0"
                                class="button sheme__tabs-title-button js-tabs-title is-active">
                            <span class="button__text">До гостиницы</span>
                        </button>
                    </div>
                    <div class="sheme__tabs-title">
                        <button type="button" data-tab-index="1" class="button sheme__tabs-title-button js-tabs-title">
                            <span class="button__text">До п. Бетта</span>
                        </button>
                    </div>
                </div>

                <div class="sheme__tabs-bodys">
                    <div class="sheme__tabs-body js-tabs-body is-active" data-tab-index="0">
                        <div class="sheme__tabs-map">
                            <script
                                src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A920c7aaba0dfe13ca9d9c2ab7835c59ce66a65874f3ccb5e6d398d761b49f8b2&amp;width=100%&amp;height=100%&amp;lang=ru_RU&amp;scroll=true"
                                type="text/javascript"></script>
                        </div>
                    </div>
<!--                    <div class="sheme__tabs-body js-tabs-body" data-tab-index="1">-->
<!--                        <div class="sheme__tabs-map">-->
<!--                            <script-->
<!--                                src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A920c7aaba0dfe13ca9d9c2ab7835c59ce66a65874f3ccb5e6d398d761b49f8b2&amp;width=100%&amp;height=100%&amp;lang=ru_RU&amp;scroll=true"-->
<!--                                type="text/javascript"></script>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </div>
</div><!-- sheme -->
<div class="contacts contacts--how-to-get">
    <div class="contacts__container container">
        <div class="contacts__content">
            <div class="contacts__items">
                <div class="contacts__items-header">
                    <div class="contacts__item">
                        <div class="contacts__item-header">Адрес:</div>
                        <div class="contacts__item-content">

                            <div class="svg-icon svg-icon--flag" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#flag"></use>
                                </svg>
                            </div>


                            <div class="contacts__item-text">Краснодарский край, Геленджикский район,<br>
                                п. Бетта, ул. Садовая, д.4Б
                            </div>
                        </div>
                    </div>

                    <div class="contacts__item">
                        <div class="contacts__item-header">Телефоны:</div>
                        <div class="contacts__item-content">

                            <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#phone-icon"></use>
                                </svg>
                            </div>


                            <div class="contacts__item-text">
                                <?php render_phones(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- contacts -->
