<div class="hero hero--inside">
    <div class="hero__bg js-app-bg" data-bg="img/hero-pick-up-bg.png"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">Курорт Бетта</h1>


            <nav class="crumbs">
                <div class="crumbs__items">

                    <div class="crumbs__item">

                        <a href="index.html" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                    </span>

                    </div>

                    <div class="crumbs__item">

                        <span href="resort-betta.html" class="crumbs__current">Курорт Бетта</span>

                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->


<div class="resort-betta-list">
    <div class="resort-betta-list__container container">
        <div class="resort-betta-list__items js-ajax-resort-items">

            <div class="resort-betta-list__item">


                <div class="resort-betta">
                    <div class="resort-betta__container">
                        <div class="resort-betta__image">
                            <a href="#" class="resort-betta__image-link">
                                <picture class="resort-betta__picture">
                                    <source srcset="img/resot-betta-pic-mobile.png" media="(max-width: 979px)"
                                            type="image/png">
                                    <source srcset="img/resot-betta-pic-desktop.png" media="(min-width: 980px)"
                                            type="image/png">
                                    <img src="img/resot-betta-pic-desktop.png" alt="">
                                </picture>
                            </a>
                        </div>
                        <div class="resort-betta__body">
                            <div class="resort-betta__title">
                                <a href="#" class="resort-betta__title-link">Прогулки на джипах</a>
                            </div>
                            <div class="resort-betta__text">Путешествие на автомобилях повышенной проходимости с
                                преодолением
                                природных препятствий. Для участия в джиппинге не требуется обладать особыми навыками. В
                                них может
                                принять участие любой, кто желает получить незабываемые впечатления.
                            </div>
                            <div class="resort-betta__meta">
                                <div class="resort-betta__meta-col resort-betta__meta-col--price">
                                    <div class="resort-betta__meta-item resort-betta__meta-item--price">


                                        <div class="svg-icon svg-icon--price" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#price"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">550 руб / 1 взрослый</div>
                                            <div class="resort-betta__meta-text">350 руб / 1 детский (до 14 лет)</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="resort-betta__meta-col resort-betta__meta-col--info">
                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--clock" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#clock"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">180 минут</div>
                                        </div>
                                    </div>

                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>

                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">
                                                <a href="tel:+79273333333" class="resort-betta__meta-phone">+7 927 333
                                                    33 33</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- resort-betta -->
            </div>

            <div class="resort-betta-list__item">


                <div class="resort-betta">
                    <div class="resort-betta__container">
                        <div class="resort-betta__image">
                            <a href="#" class="resort-betta__image-link">
                                <picture class="resort-betta__picture">
                                    <source srcset="img/resot-betta-pic-mobile.png" media="(max-width: 979px)"
                                            type="image/png">
                                    <source srcset="img/resot-betta-pic-desktop.png" media="(min-width: 980px)"
                                            type="image/png">
                                    <img src="img/resot-betta-pic-desktop.png" alt="">
                                </picture>
                            </a>
                        </div>
                        <div class="resort-betta__body">
                            <div class="resort-betta__title">
                                <a href="#" class="resort-betta__title-link">Прогулки на джипах</a>
                            </div>
                            <div class="resort-betta__text">Путешествие на автомобилях повышенной проходимости с
                                преодолением
                                природных препятствий. Для участия в джиппинге не требуется обладать особыми навыками. В
                                них может
                                принять участие любой, кто желает получить незабываемые впечатления.
                            </div>
                            <div class="resort-betta__meta">
                                <div class="resort-betta__meta-col resort-betta__meta-col--price">
                                    <div class="resort-betta__meta-item resort-betta__meta-item--price">


                                        <div class="svg-icon svg-icon--price" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#price"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">550 руб / 1 взрослый</div>
                                            <div class="resort-betta__meta-text">350 руб / 1 детский (до 14 лет)</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="resort-betta__meta-col resort-betta__meta-col--info">
                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--clock" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#clock"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">180 минут</div>
                                        </div>
                                    </div>

                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>

                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">
                                                <a href="tel:+79273333333" class="resort-betta__meta-phone">+7 927 333
                                                    33 33</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- resort-betta -->
            </div>

            <div class="resort-betta-list__item">


                <div class="resort-betta">
                    <div class="resort-betta__container">
                        <div class="resort-betta__image">
                            <a href="#" class="resort-betta__image-link">
                                <picture class="resort-betta__picture">
                                    <source srcset="img/resot-betta-pic-mobile.png" media="(max-width: 979px)"
                                            type="image/png">
                                    <source srcset="img/resot-betta-pic-desktop.png" media="(min-width: 980px)"
                                            type="image/png">
                                    <img src="img/resot-betta-pic-desktop.png" alt="">
                                </picture>
                            </a>
                        </div>
                        <div class="resort-betta__body">
                            <div class="resort-betta__title">
                                <a href="#" class="resort-betta__title-link">Прогулки на джипах</a>
                            </div>
                            <div class="resort-betta__text">Путешествие на автомобилях повышенной проходимости с
                                преодолением
                                природных препятствий. Для участия в джиппинге не требуется обладать особыми навыками. В
                                них может
                                принять участие любой, кто желает получить незабываемые впечатления.
                            </div>
                            <div class="resort-betta__meta">
                                <div class="resort-betta__meta-col resort-betta__meta-col--price">
                                    <div class="resort-betta__meta-item resort-betta__meta-item--price">


                                        <div class="svg-icon svg-icon--price" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#price"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">550 руб / 1 взрослый</div>
                                            <div class="resort-betta__meta-text">350 руб / 1 детский (до 14 лет)</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="resort-betta__meta-col resort-betta__meta-col--info">
                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--clock" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#clock"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">180 минут</div>
                                        </div>
                                    </div>

                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>

                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">
                                                <a href="tel:+79273333333" class="resort-betta__meta-phone">+7 927 333
                                                    33 33</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- resort-betta -->
            </div>

            <div class="resort-betta-list__item">


                <div class="resort-betta">
                    <div class="resort-betta__container">
                        <div class="resort-betta__image">
                            <a href="#" class="resort-betta__image-link">
                                <picture class="resort-betta__picture">
                                    <source srcset="img/resot-betta-pic-mobile.png" media="(max-width: 979px)"
                                            type="image/png">
                                    <source srcset="img/resot-betta-pic-desktop.png" media="(min-width: 980px)"
                                            type="image/png">
                                    <img src="img/resot-betta-pic-desktop.png" alt="">
                                </picture>
                            </a>
                        </div>
                        <div class="resort-betta__body">
                            <div class="resort-betta__title">
                                <a href="#" class="resort-betta__title-link">Прогулки на джипах</a>
                            </div>
                            <div class="resort-betta__text">Путешествие на автомобилях повышенной проходимости с
                                преодолением
                                природных препятствий. Для участия в джиппинге не требуется обладать особыми навыками. В
                                них может
                                принять участие любой, кто желает получить незабываемые впечатления.
                            </div>
                            <div class="resort-betta__meta">
                                <div class="resort-betta__meta-col resort-betta__meta-col--price">
                                    <div class="resort-betta__meta-item resort-betta__meta-item--price">


                                        <div class="svg-icon svg-icon--price" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#price"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">550 руб / 1 взрослый</div>
                                            <div class="resort-betta__meta-text">350 руб / 1 детский (до 14 лет)</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="resort-betta__meta-col resort-betta__meta-col--info">
                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--clock" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#clock"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">180 минут</div>
                                        </div>
                                    </div>

                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>

                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">
                                                <a href="tel:+79273333333" class="resort-betta__meta-phone">+7 927 333
                                                    33 33</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- resort-betta -->
            </div>

            <div class="resort-betta-list__item">


                <div class="resort-betta">
                    <div class="resort-betta__container">
                        <div class="resort-betta__image">
                            <a href="#" class="resort-betta__image-link">
                                <picture class="resort-betta__picture">
                                    <source srcset="img/resot-betta-pic-mobile.png" media="(max-width: 979px)"
                                            type="image/png">
                                    <source srcset="img/resot-betta-pic-desktop.png" media="(min-width: 980px)"
                                            type="image/png">
                                    <img src="img/resot-betta-pic-desktop.png" alt="">
                                </picture>
                            </a>
                        </div>
                        <div class="resort-betta__body">
                            <div class="resort-betta__title">
                                <a href="#" class="resort-betta__title-link">Прогулки на джипах</a>
                            </div>
                            <div class="resort-betta__text">Путешествие на автомобилях повышенной проходимости с
                                преодолением
                                природных препятствий. Для участия в джиппинге не требуется обладать особыми навыками. В
                                них может
                                принять участие любой, кто желает получить незабываемые впечатления.
                            </div>
                            <div class="resort-betta__meta">
                                <div class="resort-betta__meta-col resort-betta__meta-col--price">
                                    <div class="resort-betta__meta-item resort-betta__meta-item--price">


                                        <div class="svg-icon svg-icon--price" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#price"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">550 руб / 1 взрослый</div>
                                            <div class="resort-betta__meta-text">350 руб / 1 детский (до 14 лет)</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="resort-betta__meta-col resort-betta__meta-col--info">
                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--clock" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#clock"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">180 минут</div>
                                        </div>
                                    </div>

                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>

                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">
                                                <a href="tel:+79273333333" class="resort-betta__meta-phone">+7 927 333
                                                    33 33</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- resort-betta -->
            </div>

            <div class="resort-betta-list__item">


                <div class="resort-betta">
                    <div class="resort-betta__container">
                        <div class="resort-betta__image">
                            <a href="#" class="resort-betta__image-link">
                                <picture class="resort-betta__picture">
                                    <source srcset="img/resot-betta-pic-mobile.png" media="(max-width: 979px)"
                                            type="image/png">
                                    <source srcset="img/resot-betta-pic-desktop.png" media="(min-width: 980px)"
                                            type="image/png">
                                    <img src="img/resot-betta-pic-desktop.png" alt="">
                                </picture>
                            </a>
                        </div>
                        <div class="resort-betta__body">
                            <div class="resort-betta__title">
                                <a href="#" class="resort-betta__title-link">Прогулки на джипах</a>
                            </div>
                            <div class="resort-betta__text">Путешествие на автомобилях повышенной проходимости с
                                преодолением
                                природных препятствий. Для участия в джиппинге не требуется обладать особыми навыками. В
                                них может
                                принять участие любой, кто желает получить незабываемые впечатления.
                            </div>
                            <div class="resort-betta__meta">
                                <div class="resort-betta__meta-col resort-betta__meta-col--price">
                                    <div class="resort-betta__meta-item resort-betta__meta-item--price">


                                        <div class="svg-icon svg-icon--price" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#price"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">550 руб / 1 взрослый</div>
                                            <div class="resort-betta__meta-text">350 руб / 1 детский (до 14 лет)</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="resort-betta__meta-col resort-betta__meta-col--info">
                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--clock" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#clock"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">180 минут</div>
                                        </div>
                                    </div>

                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>

                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">
                                                <a href="tel:+79273333333" class="resort-betta__meta-phone">+7 927 333
                                                    33 33</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- resort-betta -->
            </div>

            <div class="resort-betta-list__item">


                <div class="resort-betta">
                    <div class="resort-betta__container">
                        <div class="resort-betta__image">
                            <a href="#" class="resort-betta__image-link">
                                <picture class="resort-betta__picture">
                                    <source srcset="img/resot-betta-pic-mobile.png" media="(max-width: 979px)"
                                            type="image/png">
                                    <source srcset="img/resot-betta-pic-desktop.png" media="(min-width: 980px)"
                                            type="image/png">
                                    <img src="img/resot-betta-pic-desktop.png" alt="">
                                </picture>
                            </a>
                        </div>
                        <div class="resort-betta__body">
                            <div class="resort-betta__title">
                                <a href="#" class="resort-betta__title-link">Прогулки на джипах</a>
                            </div>
                            <div class="resort-betta__text">Путешествие на автомобилях повышенной проходимости с
                                преодолением
                                природных препятствий. Для участия в джиппинге не требуется обладать особыми навыками. В
                                них может
                                принять участие любой, кто желает получить незабываемые впечатления.
                            </div>
                            <div class="resort-betta__meta">
                                <div class="resort-betta__meta-col resort-betta__meta-col--price">
                                    <div class="resort-betta__meta-item resort-betta__meta-item--price">


                                        <div class="svg-icon svg-icon--price" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#price"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">550 руб / 1 взрослый</div>
                                            <div class="resort-betta__meta-text">350 руб / 1 детский (до 14 лет)</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="resort-betta__meta-col resort-betta__meta-col--info">
                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--clock" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#clock"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">180 минут</div>
                                        </div>
                                    </div>

                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>

                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">
                                                <a href="tel:+79273333333" class="resort-betta__meta-phone">+7 927 333
                                                    33 33</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- resort-betta -->
            </div>

            <div class="resort-betta-list__item">


                <div class="resort-betta">
                    <div class="resort-betta__container">
                        <div class="resort-betta__image">
                            <a href="#" class="resort-betta__image-link">
                                <picture class="resort-betta__picture">
                                    <source srcset="img/resot-betta-pic-mobile.png" media="(max-width: 979px)"
                                            type="image/png">
                                    <source srcset="img/resot-betta-pic-desktop.png" media="(min-width: 980px)"
                                            type="image/png">
                                    <img src="img/resot-betta-pic-desktop.png" alt="">
                                </picture>
                            </a>
                        </div>
                        <div class="resort-betta__body">
                            <div class="resort-betta__title">
                                <a href="#" class="resort-betta__title-link">Прогулки на джипах</a>
                            </div>
                            <div class="resort-betta__text">Путешествие на автомобилях повышенной проходимости с
                                преодолением
                                природных препятствий. Для участия в джиппинге не требуется обладать особыми навыками. В
                                них может
                                принять участие любой, кто желает получить незабываемые впечатления.
                            </div>
                            <div class="resort-betta__meta">
                                <div class="resort-betta__meta-col resort-betta__meta-col--price">
                                    <div class="resort-betta__meta-item resort-betta__meta-item--price">


                                        <div class="svg-icon svg-icon--price" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#price"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">550 руб / 1 взрослый</div>
                                            <div class="resort-betta__meta-text">350 руб / 1 детский (до 14 лет)</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="resort-betta__meta-col resort-betta__meta-col--info">
                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--clock" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#clock"></use>
                                            </svg>
                                        </div>


                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">180 минут</div>
                                        </div>
                                    </div>

                                    <div class="resort-betta__meta-item">


                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>

                                        <div class="resort-betta__meta-data">
                                            <div class="resort-betta__meta-text">
                                                <a href="tel:+79273333333" class="resort-betta__meta-phone">+7 927 333
                                                    33 33</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- resort-betta -->
            </div>

        </div>
    </div>
</div><!-- resort-betta -->
<div class="ajax-loader js-ajax-loader is-hidden" data-target=".js-ajax-resort-items"
     data-url="api/resort/ajax-resort.html">
    <div class="ajax-loader__preloader">
        <div class="ajax-loader__items">
            <div class="ajax-loader__item"></div>
            <div class="ajax-loader__item"></div>
            <div class="ajax-loader__item"></div>
        </div>
    </div>
</div><!-- ajax-loader -->
