<div class="hero hero--inside">
    <div class="hero__bg js-app-bg" data-bg="<?= page_config('hero_image') ?>"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">Для гостей</h1>


            <nav class="crumbs">
                <div class="crumbs__items">

                    <div class="crumbs__item">
                        <a href="/" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">
                            <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#arrorw-right"></use>
                                </svg>
                            </span>
                        </span>
                    </div>

                    <div class="crumbs__item">
                        <span class="crumbs__current">Для гостей</span>
                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->


<div class="resort-betta-list">
    <div class="resort-betta-list__container container">

        <p>Бетта - небольшой курорт в окружении девственной природы с глубокими ущельями, густыми лесами, галечными
            пляжами и теплым прозрачным морем. Попадая в этот райский уголок, забываешь обо всем и первые несколько
            дней хочется изучить каждый его метр.</p>


        <p>Но хороший отдых на море - не только пляжи и уютные кафе. Он состоит из мелочей. Мы сделали все, чтобы
            каждая минута пребывания в Resort-Betta приносила удовольствие.</p>


        <p>Гордость Курорта-Бетта - комфортабельные номера. Но еще мы позаботились о разнообразии досуга и бытовых
            мелочах для гостей. Вокруг комплекса красивый ландшафтный дизайн, создана уютная обстановка, где можно
            провести время большой компанией или подумать наедине. На огражденной территории:</p>

        <div class="services__wrapper">
            <div class="about__body">
                <div class="about__image">
                    <img src="/img/services/playground.jpg" alt="">
                </div>

                <div class="about__content">
                    <div class="about__text">
                        <h3 class="about__title">Детская площадка</h3>

                        <div class="about__text__inner">
                            <p>Горка выглядит как сказочный теремок и станет эпицентром детских забав. На нижнем ярусе
                                внутри уютного домика есть лавочки со столиком, после активных игр дети смогут перейти к
                                более спокойному отдыху. Рядом качели, без которых свою жизнь не представляет ни один
                                ребенок. Зона расположилась перед жилым корпусом с апартаментами. Ребятня всегда на виду
                                у взрослых.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="about__body service__reverse">
                <div class="about__image">
                    <img src="/img/services/pavilion.jpg" alt="">
                </div>

                <div class="about__content">
                    <div class="about__text">
                        <h3 class="about__title">Мангал</h3>

                        <div class="about__text__inner">
                            <p>Без чего сложно представить отдых на море? Правильно, без ароматного шашлыка, рыбки на
                                гриле.
                                Мы
                                обустроили крытые беседки с мангалом-печью - никакого дыма в лицо. Подведена вода,
                                водосток,
                                в
                                распоряжении набор кухонных принадлежностей.</p>
                            <p> Мангальные зоны расположены на территории комплекса, огражденной заборчиком. Непрошенные
                                гости не
                                испортят отдых. Бесплатно для наших постояльцев.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="about__body">
                <div class="about__image">
                    <img src="/img/services/ping-pong.jpg" alt="">
                </div>

                <div class="about__content">
                    <div class="about__text">
                        <h3 class="about__title">Настольный теннис</h3>

                        <div class="about__text__inner">

                            <p>Не хочется сидеть в комнате теплыми вечерами? Мы за активный отдых и установили во дворе
                                теннисный стол.
                                Можно взять свои ракетки или попросить у администрации.</p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="about__body service__reverse">
                <div class="about__image">
                    <img src="/img/services/cars.jpg" alt="">
                </div>

                <div class="about__content">
                    <div class="about__text">
                        <h3 class="about__title">Парковка</h3>

                        <div class="about__text__inner">
                            <p>Просторная парковка на закрытой территории. Есть места для авто под навесом в тени от
                                виноградной лозы,
                                защищающей от южного солнца и рядом с жилыми корпусами.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="about__body">
                <div class="about__image">
                    <img src="/img/services/hozblock.jpg" alt="">
                </div>

                <div class="about__content">
                    <div class="about__text">
                        <h3 class="about__title">Хозяйственный блок</h3>

                        <div class="about__text__inner">
                            <p>Хотите освежить одежду? Для гостей мы установили стиральные машины в отдельном хозблоке.
                                Услуга
                                бесплатная для всех постояльцев, независимо от времени пребывания.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="about__body service__reverse">
                <div class="about__image">
                    <img src="/img/services/bath.jpg" alt="">
                </div>

                <div class="about__content">
                    <div class="about__text">
                        <h3 class="about__title">Баня...</h3>

                        <div class="about__text__inner">
                            <p>Это место, где можно омыть не только тело, но и отдохнуть душой. Отличный способ провести
                                время, если
                                вдруг на отдыхе вас застал дождь или прохладная погода.</p>


                            <p>Уютная баня с большим предбанником и бассейном, где можно устроить романтический вечер
                                или
                                посиделки
                                дружной компании. Чтобы заказать отдых, подойдите к администратору. Поскольку на
                                подготовку
                                нужны
                                большие затраты, это единственная платная услуга в нашем гостевом комплексе.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- resort-betta -->
