<!-- Primary Meta Tags -->
<meta name="title" content="Курорт Бетта - Marmelad v6.10.4 / master">
<meta name="description" content="Заготовка фронтенд проекта для продвинутых и начинающих 🤘">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://github.com/solversgroup/marmelad">
<meta property="og:title" content="Курорт Бетта">
<meta property="og:description" content="Заготовка фронтенд проекта для продвинутых и начинающих 🤘">
<meta property="og:image" content="https://github.com/solversgroup/marmelad/blob/master/marmelad.svg?sanitize=true">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://github.com/solversgroup/marmelad">
<meta property="twitter:title" content="Курорт Бетта">
<meta property="twitter:description" content="Заготовка фронтенд проекта для продвинутых и начинающих 🤘">
<meta property="twitter:image"
      content="https://github.com/solversgroup/marmelad/blob/master/marmelad.svg?sanitize=true">


<title>Курорт Бетта - Marmelad v6.10.4 / master</title>