<div class="hero hero--inside">
    <div class="hero__bg js-app-bg" data-bg="<?= page_config('hero_image') ?>"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">О нас</h1>

            <nav class="crumbs">
                <div class="crumbs__items">

                    <div class="crumbs__item">

                        <a href="/" class="crumbs__link">Главная</a>

                        <span class="crumbs__sep">
                          <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
                            <svg class="svg-icon__link">
                              <use xlink:href="#arrorw-right"></use>
                            </svg>
                          </span>
                        </span>
                    </div>

                    <div class="crumbs__item">
                        <span href="/about-us" class="crumbs__current">О нас</span>
                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->

<div class="home-about">
    <div class="home-about__container container">


        <div class="about">
            <div class="about__header h1">Курорт Бетта</div>
            <div class="about__body">
                <div class="about__image"><img src="img/about.png" alt=""></div>
                <div class="about__content">
                    <div class="about__text">

      <span class="svg-icon svg-icon--about-text-icon" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#about-text-icon"></use>
        </svg>
      </span>
                        <p>Наш комплекс предлагает просторные одно и двухкомнатные апартаменты в сердце курорта Бетта -
                            заповедной зоне на Кубани. Большой двор с зонами для мангала и беседками для безмятежного
                            отдыха на свежем воздухе теплыми вечерами. Отдельная парковка, где хватит места для
                            транспорта всех гостей. И конечно же игровые площадки для самых маленьких с горками в виде
                            сказочного теремка и качелями.</p>

                        <p>Главная наша гордость - ухоженные номера-студии с небольшой кухней, удобной, стильной
                            мебелью, новой бытовой техникой. Мы следим за комнатами, как за дворцовыми палатами: каждая
                            полочка, ручка, сантехника - все в идеальном состоянии. Для нас каждый гость, даже если
                            планируете арендовать апартаменты на одну ночь - наследник престола. И мы сделаем все, чтобы
                            этот отдых вы запомнили на всю жизнь. Сотрудники Resort-betta к услугам в любое время
                            суток.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="counters-about">
    <div class="counters-about__container container">
        <div class="counters-about__header">Мы в цифрах</div>
        <div class="counters-about__items">

            <div class="counters-about__item">
                <div class="counters-about__number">
                    <div id="counter-i0" class="counters-about__number-value js-counter" data-counter-up="5">5</div>
                </div>
                <div class="counters-about__title">минут <br>до моря</div>
            </div>

            <div class="counters-about__item">
                <div class="counters-about__number">
                    <div id="counter-i1" class="counters-about__number-value js-counter" data-counter-up="25">25</div>
                </div>
                <div class="counters-about__title">постоянных <br>клиентов</div>
            </div>

            <div class="counters-about__item">
                <div class="counters-about__number">
                    <div id="counter-i2" class="counters-about__number-value js-counter" data-counter-up="50">50</div>
                </div>
                <div class="counters-about__title">номеров</div>
            </div>

            <div class="counters-about__item">
                <div class="counters-about__number">
                    <div id="counter-i3" class="counters-about__number-value js-counter" data-counter-up="28">28</div>
                </div>
                <div class="counters-about__title">средняя <br>температура <br>моря</div>
            </div>

        </div>
    </div>
</div>
