<div class="hero hero--inside">
    <div class="hero__bg js-app-bg" data-bg="img/hero-pick-up-bg.png"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">О нас</h1>


            <nav class="crumbs">
                <div class="crumbs__items">

                    <div class="crumbs__item">

                        <a href="index.html" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                    </span>

                    </div>

                    <div class="crumbs__item">

                        <span href="about.html" class="crumbs__current">Курорт о нас</span>

                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->
<div class="home-about">
    <div class="home-about__container container">


        <div class="about">
            <div class="about__header h1">Курорт Бетта</div>
            <div class="about__body">
                <div class="about__image"><img src="img/about.png" alt=""></div>
                <div class="about__content">
                    <div class="about__text">

      <span class="svg-icon svg-icon--about-text-icon" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#about-text-icon"></use>
        </svg>
      </span>

                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et
                        dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                        aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum
                        dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa
                        qui
                        officia deserunt mollit anim id est laborum.
                    </div>
                    <div class="about__more">
                        <a href="#1" class="button button--arrow about__link">
                            <span class="button__text">Подробнее</span>

                            <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                        </a><!-- b:button -->
                    </div>
                </div>
            </div>
        </div><!-- about -->
    </div>
</div><!-- home-about -->


<div class="counters-about">
    <div class="counters-about__container container">
        <div class="counters-about__header">Мы в цифрах</div>
        <div class="counters-about__items">

            <div class="counters-about__item">
                <div class="counters-about__number">
                    <div id="counter-i0" class="counters-about__number-value js-counter" data-counter-up="5">5</div>
                </div>
                <div class="counters-about__title">минут <br>до моря</div>
            </div>

            <div class="counters-about__item">
                <div class="counters-about__number">
                    <div id="counter-i1" class="counters-about__number-value js-counter" data-counter-up="25">25</div>
                </div>
                <div class="counters-about__title">постоянных <br>клиентов</div>
            </div>

            <div class="counters-about__item">
                <div class="counters-about__number">
                    <div id="counter-i2" class="counters-about__number-value js-counter" data-counter-up="50">50</div>
                </div>
                <div class="counters-about__title">номеров</div>
            </div>

            <div class="counters-about__item">
                <div class="counters-about__number">
                    <div id="counter-i3" class="counters-about__number-value js-counter" data-counter-up="28">28</div>
                </div>
                <div class="counters-about__title">средняя <br>температура <br>моря</div>
            </div>

        </div>
    </div>
</div><!-- counters-about -->