<div class="hero hero--inside">
    <div class="hero__bg js-app-bg" data-bg="img/hero-pick-up-bg.png"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">Бронирование</h1>


            <nav class="crumbs">
                <div class="crumbs__items">

                    <div class="crumbs__item">

                        <a href="index.html" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                    </span>

                    </div>

                    <div class="crumbs__item">

                        <span href="reservation.html" class="crumbs__current">Бронирование</span>

                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->

<form class="selection"> <!-- selection--reservation todo стиль ля выбранного числа !! Нужно? -->
    <div class="selection__container container">
        <div class="selection__content">
            <div class="selection__header">Мы поможем подобрать вам подходящий номер</div>


            <div class="counter selection__counter js-ipnut-spinner">

                <div class="counter__header">Количество отдыхающих</div>


                <div class="counter__content">
                    <div class="counter__icon">

                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                            <svg class="svg-icon__link">
                                <use xlink:href="#counter-icon"></use>
                            </svg>
                        </div>

                    </div>
                    <div class="counter__reservation">
                        <div class="counter__selected">2</div>
                        <button type="button" class="counter__change js-counter-change">Изменить</button>
                    </div>
                    <div class="counter__controls">
                        <button type="button" class="counter__button counter__button--minus js-input-spinner-minus">
                            <span class="counter__button-text">-</span>
                        </button>
                        <input value="2" required="" data-maxlength="2" type="number" name="persons"
                               class="counter__input js-input-spinner-counter">
                        <button type="button" class="counter__button counter__button--plus js-input-spinner-plus">
                            <span class="counter__button-text">+</span>
                        </button>
                    </div>
                </div>
            </div><!-- counter -->

            <div class="selection__button">
                <button type="submit" class="button button--large selection__submit js-selection-submit">Подобрать номер
                </button><!-- button -->
            </div>
        </div>
    </div>
</form><!-- selection -->


<div class="apartments apartments--reservation">


    <div class="apartments__body">
        <div class="apartments__body-inside">
            <div class="apartments__body-container">
                <div class="apartments__items js-ajax-apartments-items">

                    <div hidden class="apartments__item" data-persons-count="1-2">


                        <div class="apartment apartment--reservation js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом</div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ, кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                    <div hidden class="apartments__item" data-persons-count="3-3">


                        <div class="apartment apartment--reservation js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png" media="(max-width: 979px)" type="image/png">

                                        <source srcset="img/apartment-image-resevation.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image-resevation.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом</div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-5</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ, кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>


                </div>
            </div>
        </div>
    </div>


</div><!-- apartments -->


<div class="ajax-loader js-ajax-loader is-hidden" data-target=".js-ajax-apartments-items"
     data-url="api/apartments/ajax-apartments.html">
    <div class="ajax-loader__preloader">
        <div class="ajax-loader__items">
            <div class="ajax-loader__item"></div>
            <div class="ajax-loader__item"></div>
            <div class="ajax-loader__item"></div>
        </div>
    </div>
</div><!-- ajax-loader -->