<div class="hero hero--inside">
    <div class="hero__bg js-app-bg" data-bg="<?=page_config('hero_image')?>"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">Бронирование</h1>


            <nav class="crumbs">
                <div class="crumbs__items">

                    <div class="crumbs__item">
                        <a href="/" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">
                          <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
                            <svg class="svg-icon__link">
                              <use xlink:href="#arrorw-right"></use>
                            </svg>
                          </span>
                        </span>
                    </div>

                    <div class="crumbs__item">

                        <span href="/reservation" class="crumbs__current">Бронирование</span>

                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->

<form class="selection" hidden>
    <div class="selection__container container">
        <div class="selection__content">
            <div class="selection__header">Мы поможем подобрать подходящий вам номер</div>

            <div class="counter selection__counter js-ipnut-spinner">

                <div class="counter__header">Количество отдыхающих</div>


                <div class="counter__content">
                    <div class="counter__icon">

                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                            <svg class="svg-icon__link">
                                <use xlink:href="#counter-icon"></use>
                            </svg>
                        </div>

                    </div>
                    <div class="counter__reservation">
                        <div class="counter__selected">2</div>
                        <button type="button" class="counter__change js-counter-change">Изменить</button>
                    </div>
                    <div class="counter__controls">
                        <button type="button" class="counter__button counter__button--minus js-input-spinner-minus">
                            <span class="counter__button-text">-</span>
                        </button>
                        <input value="2" required="" data-maxlength="2" type="number" name="persons"
                               class="counter__input js-input-spinner-counter">
                        <button type="button" class="counter__button counter__button--plus js-input-spinner-plus">
                            <span class="counter__button-text">+</span>
                        </button>
                    </div>
                </div>
            </div><!-- counter -->

            <div class="selection__button">
                <button type="submit" class="button button--large selection__submit js-selection-submit">Подобрать номер
                </button><!-- button -->
            </div>
        </div>
    </div>
</form><!-- selection -->


<div class="apartments apartments--reservation">


    <div class="apartments__body">
        <div class="apartments__body-inside">
            <div class="apartments__body-container">
                <div class="apartments__items js-ajax-apartments-items">

                    <?
                    require 'apartment_list_item.php';
                    render_apartments_list();
                    ?>

                </div>
            </div>
        </div>
    </div>


</div><!-- apartments -->


<div class="ajax-loader js-ajax-loader is-hidden" data-target=".js-ajax-apartments-items"
     data-url="api/apartments/ajax-apartments.html">
    <div class="ajax-loader__preloader">
        <div class="ajax-loader__items">
            <div class="ajax-loader__item"></div>
            <div class="ajax-loader__item"></div>
            <div class="ajax-loader__item"></div>
        </div>
    </div>
</div><!-- ajax-loader -->
