<div class="hero">
    <div class="hero__bg js-app-bg" data-bg="img/hero-bg.png"></div>

    <div class="hero__content">
        <div class="hero__text">
            <h1 class="hero__header h1">Начните свое<br> путешествие в Бетте</h1>
            <p>Лучшие воспоминания начинаются здесь</p>
        </div>
    </div>
</div><!-- hero -->

<form class="selection" action="reservation"> <!-- todo Display a list of numbers on the current page. Like SPA-style -->
    <div class="selection__container container">
        <div class="selection__content">
            <div class="selection__header">Мы поможем подобрать подходящий вам номер</div>


            <div class="counter selection__counter js-ipnut-spinner">

                <div class="counter__header">Количество отдыхающих</div>


                <div class="counter__content">
                    <div class="counter__icon">

                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                            <svg class="svg-icon__link">
                                <use xlink:href="#counter-icon"></use>
                            </svg>
                        </div>

                    </div>
                    <div class="counter__reservation">
                        <div class="counter__selected"></div>
                        <button type="button" class="counter__change js-counter-change">Изменить</button>
                    </div>
                    <div class="counter__controls">
                        <button type="button" class="counter__button counter__button--minus js-input-spinner-minus">
                            <span class="counter__button-text">-</span>
                        </button>
                        <input value="2" required="" data-maxlength="2" type="number" name="persons"
                               class="counter__input js-input-spinner-counter">
                        <button type="button" class="counter__button counter__button--plus js-input-spinner-plus">
                            <span class="counter__button-text">+</span>
                        </button>
                    </div>
                </div>
            </div><!-- counter -->

            <div class="selection__button">
                <button type="submit" class="button button--large selection__submit js-selection-submit">Подобрать номер
                </button><!-- button -->
            </div>
        </div>
    </div>
</form><!-- selection -->

<div class="home-about">
    <div class="home-about__container container">


        <div class="about">
            <div class="about__header h1">Курорт Бетта</div>
            <div class="about__body">
                <div class="about__image"><img src="img/about.png" alt=""></div>
                <div class="about__content">
                    <div class="about__text">

      <span class="svg-icon svg-icon--about-text-icon" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#about-text-icon"></use>
        </svg>

          <!-- FIXME rewrite this -->
      </span>Бетта — живописный курортный посёлок у берега открытого моря, один из самых уединённых уголков на
                        побережье. Все крупные транспортные магистрали, как автомобильные, так и морские, сильно удалены
                        от
                        этого мини-курорта. Отдых в Бетте, однако, можно считать весьма цивилизованным (высокого уровня
                        комфортности). На центральном пляже Бетты Вы найдёте все привычные курортные развлечения,
                        набережную с
                        ресторанами и кафе. Если не пожалеть сил и отойти от центрального пляжа на несколько сот метров,
                        можно
                        отыскать совсем безлюдные дикие пляжи, полюбоваться окрестными скалами и хвойными лесами...
                    </div>
                    <div class="about__more">
                        <a href="/about-us" class="button button--arrow about__link">
                            <span class="button__text">Подробнее</span>

                            <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                        </a><!-- b:button -->
                    </div>
                </div>
            </div>
        </div><!-- about -->
    </div>
</div><!-- home-about -->

<div class="apartments">

    <div class="apartments__headline container">
        <div class="apartments__header">Номера</div>


        <div class="apartments__more apartments__more--desktop">
            <a href="#1" class="button button--arrow apartments__link">
                <span class="button__text">Все номера</span>

                <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

            </a><!-- b:button -->
        </div>

    </div>


    <div class="apartments__body">
        <div class="apartments__body-inside">
            <div class="apartments__body-container">
                <div class="apartments__items">

                    <div class="apartments__item">


                        <div class="apartment js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом
                                        </div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon"
                                                     aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored"
                                                 aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                    <div class="apartments__item">


                        <div class="apartment js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом
                                        </div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon"
                                                     aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored"
                                                 aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                    <div class="apartments__item">


                        <div class="apartment js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="img/apartment-image@960.png"
                                                media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом
                                        </div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon"
                                                     aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored"
                                                 aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                </div>
            </div>
        </div>
    </div>


    <div class="apartments__more apartments__more--mobile container">
        <a href="#1" class="button button--arrow apartments__link">
            <span class="button__text">Все номера</span>

            <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

        </a><!-- b:button -->
    </div>

</div><!-- apartments -->