<!-- Primary Meta Tags -->
<meta name="title" content="Главная">
<meta name="description" content="Отдых в Бетте с Resort-betta">

<!-- Open Graph / Facebook -->
<!-- FIXME рассмотреть варинат добавления -->
<!--<meta property="og:type" content="website">-->
<!--<meta property="og:url" content="https://github.com/solversgroup/marmelad">-->
<!--<meta property="og:title" content="Главная">-->
<!--<meta property="og:description" content="Заготовка фронтенд проекта для продвинутых и начинающих 🤘">-->
<!--<meta property="og:image" content="https://github.com/solversgroup/marmelad/blob/master/marmelad.svg?sanitize=true">-->

<!-- Twitter -->
<!-- FIXME рассмотреть варинат добавления -->
<!--<meta property="twitter:card" content="summary_large_image">-->
<!--<meta property="twitter:url" content="https://github.com/solversgroup/marmelad">-->
<!--<meta property="twitter:title" content="Главная">-->
<!--<meta property="twitter:description" content="Заготовка фронтенд проекта для продвинутых и начинающих 🤘">-->
<!--<meta property="twitter:image"-->
<!--      content="https://github.com/solversgroup/marmelad/blob/master/marmelad.svg?sanitize=true">-->


<title>Главная</title>
