<?
// FIXME for debug
print_r(get_URL_page_params())
?>


<div class="hero hero--inside hero--card">
    <div class="hero__bg js-app-bg" data-bg="/img/hero-pick-up-bg.png"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">Двухместный номер с балконом</h1>


            <nav class="crumbs">
                <div class="crumbs__items">
                    <div class="crumbs__item">

                        <a href="index.html" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">
                            <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#arrorw-right"></use>
                                </svg>
                            </span>
                        </span>
                    </div>

                    <div class="crumbs__item">

                        <a href="reservation.html" class="crumbs__link">Бронирование</a>
                        <span class="crumbs__sep">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                    </span>

                    </div>

                    <div class="crumbs__item">

                        <span href="card.html" class="crumbs__current">Двухместный номер с балконом</span>

                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->


<div class="card">
    <div class="card__container container">
        <div class="card__content">
            <div class="card__head">
                <div class="card__title">
                    <div class="card__title-text">Двухместный номер с <br>балконом</div>


                    <div class="apartment-places card__places">
                        <div class="apartment-places__icon">

                            <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#counter-icon"></use>
                                </svg>
                            </div>

                        </div>
                        <div class="apartment-places__count">1-2</div>
                    </div>
                </div>

                <div class="card__images js-card-images">
                    <div class="card__images-counter">
                        <span class="card__images-counter-current js-card-current-slide">1</span>
                        <span class="card__images-counter-sep">из</span>
                        <span class="card__images-counter-all">5</span>
                    </div>
                    <div class="card__images-gallery js-card-images-gallery">

                        <picture class="card__image">
                            <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                            <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                            <img src="/img/card-pic-desktop.png" alt="">
                        </picture>

                        <picture class="card__image">
                            <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                            <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                            <img src="/img/card-pic-desktop.png" alt="">
                        </picture>

                        <picture class="card__image">
                            <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                            <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                            <img src="/img/card-pic-desktop.png" alt="">
                        </picture>

                        <picture class="card__image">
                            <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                            <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                            <img src="/img/card-pic-desktop.png" alt="">
                        </picture>

                        <picture class="card__image">
                            <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                            <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                            <img src="/img/card-pic-desktop.png" alt="">
                        </picture>

                    </div>
                </div>
            </div>

            <div class="card__body">
                <div class="card__right">
                    <!-- noindex -->
                    <div class="card__title">
                        <div class="card__title-text">Двухместный номер с <br>балконом</div>


                        <div class="apartment-places card__places">
                            <div class="apartment-places__icon">

                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                    <svg class="svg-icon__link">
                                        <use xlink:href="#counter-icon"></use>
                                    </svg>
                                </div>

                            </div>
                            <div class="apartment-places__count">1-2</div>
                        </div>
                    </div>
                    <!-- /noindex -->

                    <div class="card__data">
                        <div class="card__adds">

                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#check"></use>
                                </svg>
                            </div>

                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ, кондиционер, кухня, сейф
                        </div>

                        <div class="card__table">
                            <div class="card__table-head">
                                <div class="card__table-row">
                                    <div class="card__table-col"><span>Период</span></div>
                                    <div class="card__table-col"><span>Цена за номер</span></div>
                                </div>
                            </div>

                            <div class="card__table-body">
                                <div class="card__table-row">
                                    <div class="card__table-col"><span>Июнь</span></div>
                                    <div class="card__table-col"><span>1500 Р / сутки</span></div>
                                </div>
                                <div class="card__table-row">
                                    <div class="card__table-col"><span>Июль</span></div>
                                    <div class="card__table-col"><span>2000 Р / сутки</span></div>
                                </div>
                                <div class="card__table-row">
                                    <div class="card__table-col"><span>Август</span></div>
                                    <div class="card__table-col"><span>2000 Р / сутки</span></div>
                                </div>
                                <div class="card__table-row">
                                    <div class="card__table-col"><span>Сентябрь</span></div>
                                    <div class="card__table-col"><span>1500 Р / сутки</span></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card__form">
                        <div class="card__form-open">
                            <button type="button" class="button card__form-open-button js-form-open">
                                <span class="button__text">Забронировать</span>
                            </button>
                        </div>
                        <form class="form js-form">
                            <div class="form__head">
                                <div class="form__title">Забронируйте этот номер</div>
                                <div class="form__subtitle">и наши специалисты свяжутся с вами</div>
                            </div>

                            <div class="form__items">
                                <div class="form__item">
                                    <input required="" name="name" placeholder="Имя" type="text"
                                           class="input form__input">
                                </div>
                                <div class="form__item">
                                    <input required="" name="infdata" class="input form__input js-date"
                                           placeholder="Дата (Д.М - Д.М)" type="text">
                                </div>
                                <div class="form__item">
                                    <input required="" name="phone" placeholder="Телефон или e-mail" type="text"
                                           class="input form__input">
                                </div>
                                <div class="form__item">


                                    <div class="counter counter--inline form__counter js-ipnut-spinner">

                                        <div class="counter__header">Количество отдыхающих</div>


                                        <div class="counter__content">
                                            <div class="counter__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="counter__reservation">
                                                <div class="counter__selected"></div>
                                                <button type="button" class="counter__change js-counter-change">
                                                    Изменить
                                                </button>
                                            </div>
                                            <div class="counter__controls">
                                                <button type="button"
                                                        class="counter__button counter__button--minus js-input-spinner-minus">
                                                    <span class="counter__button-text">-</span>
                                                </button>
                                                <input value="" required="" data-maxlength="2" type="number"
                                                       name="persons"
                                                       class="counter__input js-input-spinner-counter">
                                                <button type="button"
                                                        class="counter__button counter__button--plus js-input-spinner-plus">
                                                    <span class="counter__button-text">+</span>
                                                </button>
                                            </div>
                                        </div>
                                    </div><!-- counter -->
                                </div>
                                <div class="form__item">
                                    <textarea name="message" placeholder="Комментарий"
                                              class="textarea form__textarea"></textarea>
                                </div>
                            </div>

                            <div class="form__button">
                                <button type="submit" class="button form__submit js-form-submit">
                                    <span class="button__text">Оставить заявку</span>
                                </button><!-- b:button -->
                            </div>

                            <div class="form__note">
                                Нажимая на кнопку, вы даете согласие на обработку своих <br>персональных данных и
                                соглашаетесь с
                                <a href="#" target="_blank">политикой <br>конфиденциальности</a>
                            </div>
                        </form><!-- form -->

                        <div class="form-thanks js-form-thanks">
                            <div class="form-thanks__image">
                                <img src="img/form-thanks.svg" alt="">
                            </div>
                            <div class="form-thanks__title">Спасибо, что выбрали нас</div>
                            <div class="form-thanks__subtitle">Наши специалисты свяжутся с вами <br>в течение 1 часа
                            </div>
                        </div><!-- b:form-thanks -->
                    </div>
                </div>

                <div class="card__left">
                    <!-- noindex -->
                    <div class="card__images js-card-images">
                        <div class="card__images-counter">
                            <span class="card__images-counter-current js-card-current-slide">1</span>
                            <span class="card__images-counter-sep">из</span>
                            <span class="card__images-counter-all">5</span>
                        </div>
                        <div class="card__images-gallery js-card-images-gallery">

                            <picture class="card__image">
                                <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                                <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                                <img src="/img/card-pic-desktop.png" alt="">
                            </picture>

                            <picture class="card__image">
                                <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                                <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                                <img src="/img/card-pic-desktop.png" alt="">
                            </picture>

                            <picture class="card__image">
                                <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                                <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                                <img src="/img/card-pic-desktop.png" alt="">
                            </picture>

                            <picture class="card__image">
                                <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                                <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                                <img src="/img/card-pic-desktop.png" alt="">
                            </picture>

                            <picture class="card__image">
                                <source srcset="/img/card-pic-mobile.png" media="(max-width: 979px)" type="image/png">
                                <source srcset="/img/card-pic-desktop.png" media="(min-width: 980px)" type="image/png">
                                <img src="/img/card-pic-desktop.png" alt="">
                            </picture>

                        </div>
                    </div>
                    <!-- /noindex -->
                    <div class="card__description">
                        <div class="card__text">
                            <div class="card__text-header">Описание:</div>
                            <div class="card__text-body">
                                <p>Номер представляет собой небольшую студию-квартиру. В номере есть небольшая кухня с
                                    холодильником, электроплитой и необходимым набором посуды. Санузлы в номерах – с
                                    душевыми
                                    кабинами. Имеется спутниковое ТВ, кондиционер, Wi-Fi, сейф, утюг, гладильная доска,
                                    сушилка.</p>
                                <p>Веранды в двухкомнатных номерах позволят уютно расположиться всей семье на трапезу.
                                    Шашлык же
                                    для этой трапезы легко приготовить на мангале в беседках возле гостиниц.</p>
                            </div>
                        </div>
                        <div class="card__meta">
                            <div class="card__meta-item">
                                <strong>Комнат:</strong> 2
                            </div>
                            <div class="card__meta-item">
                                <strong>Кухня:</strong> в номере
                            </div>
                            <div class="card__meta-item">
                                <strong>Санузел:</strong> в номере
                            </div>
                            <div class="card__meta-item">
                                <strong>Мебель:</strong> двуспальная кровать, кресло-кровать, шкаф, прикроватные
                                тумбочки, стулья,
                                стол
                            </div>
                            <div class="card__meta-item">
                                <strong>Этаж:</strong> 2
                            </div>
                        </div>

                        <div class="contacts contacts--card">
                            <div class="contacts__header">Наши контакты:</div>
                            <div class="contacts__items">
                                <div class="contacts__item">
                                    <div class="contacts__item-content">

                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>


                                        <div class="contacts__item-text">
                                            <div class="contacts__item-link">
                                                <a href="tel:">8 (960) 489 60 93 (Наталья)</a>
                                            </div>
                                            <div class="contacts__item-link">
                                                <a href="tel:">8 (988) 954 20 97</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="contacts__item">
                                    <div class="contacts__item-content">

                                        <div class="svg-icon svg-icon--envelope" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#envelope"></use>
                                            </svg>
                                        </div>


                                        <div class="contacts__item-text">
                                            <div class="contacts__item-link">
                                                <a href="mailto:admin@resort-betta.ru">admin@resort-betta.ru</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="contacts__item">
                                    <div class="contacts__item-content">

                                        <div class="svg-icon svg-icon--skype" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#skype"></use>
                                            </svg>
                                        </div>


                                        <div class="contacts__item-text">
                                            <div class="contacts__item-link">
                                                <a href="skype:admin@resort-betta.ru">n.vakary</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- contacts -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- card -->


<div class="apartments apartments--similar">

    <div class="apartments__headline container">
        <div class="apartments__header">Посмотрите также другие номера</div>


    </div>


    <div class="apartments__body">
        <div class="apartments__body-inside">
            <div class="apartments__body-container">
                <div class="apartments__items">

                    <div class="apartments__item">


                        <div class="apartment apartment--similar js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом</div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                    <div class="apartments__item">


                        <div class="apartment apartment--similar js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом</div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                    <div class="apartments__item">


                        <div class="apartment apartment--similar js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом</div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                </div>
            </div>
        </div>
    </div>


</div><!-- apartments -->