<?
require 'core/apartments.php';

$url_params = get_URL_page_params();
$apart_id = isset($url_params[0]) ? $url_params[0] : 0;

$apartment = get_apartment_by_id($apart_id);

$title =        $apartment['title'];
$min_persons =  $apartment['min_persons'];
$max_persons =  $apartment['max_persons'];
$price =        $apartment['price'];
$description =  $apartment['description'];
$facilities =   $apartment['facilities'];
$price_matrix = $apartment['price_matrix'];

$rooms_count =  $apartment['rooms_count'];
$kitchen =      $apartment['kitchen'];
$bathroom =     $apartment['bathroom'];
$furniture =    $apartment['furniture'];
$floor =        $apartment['floor'];

$apart_images = get_apartment_images($apart_id);
$img_count = $apart_images ? sizeof($apart_images) : 0;

$card_link = '/reservation/apartment/' . $apart_id;


if(is_bool($kitchen)) {
    $kitchen = $kitchen ? "в номере" : "нет";
}
if(is_bool($bathroom)) {
    $bathroom = $bathroom ? "в номере" : "нет";
}
?>


<div class="hero hero--inside hero--card">
    <div class="hero__bg js-app-bg" data-bg="<?=page_config('hero_image')?>"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1"><?=$title?></h1>


            <nav class="crumbs">
                <div class="crumbs__items">
                    <div class="crumbs__item">

                        <a href="/" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">
                            <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#arrorw-right"></use>
                                </svg>
                            </span>
                        </span>
                    </div>

                    <div class="crumbs__item">
                        <a href="/reservation" class="crumbs__link">Бронирование</a>
                        <span class="crumbs__sep">
                            <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#arrorw-right"></use>
                                </svg>
                            </span>
                        </span>
                    </div>

                    <div class="crumbs__item">
                        <span class="crumbs__current"><?=$title?></span>
                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->


<div class="card">
    <div class="card__container container">
        <div class="card__content">
            <div class="card__head">
                <div class="card__title">
                    <div class="card__title-text"><?= $title ?></div>

                    <div class="apartment-places card__places">
                        <div class="apartment-places__icon">
                            <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#counter-icon"></use>
                                </svg>
                            </div>
                        </div>
                        <div class="apartment-places__count"><?= $min_persons . '-' . $max_persons ?></div>
                    </div>
                </div>

                <div class="card__images js-card-images" <?= $img_count > 0 ? '' : 'hidden' ?>>
                    <div class="card__images-counter">
                        <span class="card__images-counter-current js-card-current-slide"><?= $img_count > 0 ? 1 : 0 ?></span>
                        <span class="card__images-counter-sep">из</span>
                        <span class="card__images-counter-all"><?= $img_count ?></span>
                    </div>
                    <div class="card__images-gallery js-card-images-gallery">
                        <?
                        if($img_count > 0) {
                            foreach ($apart_images as $k => $image) {
                                ?>
                                <picture class="card__image">
                                    <source srcset="<?= $image ?>" media="(max-width: 979px)" type="image/png">
                                    <source srcset="<?= $image ?>" media="(min-width: 980px)" type="image/png">
                                    <img       src="<?= $image ?>" alt="">
                                </picture>
                                <?
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>

            <div class="card__body">
                <div class="card__right">
                    <!-- noindex -->
                    <div class="card__title">
                        <div class="card__title-text"><?= $title ?></div>

                        <div class="apartment-places card__places">
                            <div class="apartment-places__icon">
                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                    <svg class="svg-icon__link">
                                        <use xlink:href="#counter-icon"></use>
                                    </svg>
                                </div>
                            </div>

                            <div class="apartment-places__count"><?= $min_persons . '-' . $max_persons ?></div>
                        </div>
                    </div>
                    <!-- /noindex -->

                    <div class="card__data">
                        <div class="card__adds">
                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#check"></use>
                                </svg>
                            </div>
                            <?= $facilities ?>
                        </div>

                        <div class="card__table">
                            <div class="card__table-head">
                                <div class="card__table-row">
                                    <div class="card__table-col"><span>Период</span></div>
                                    <div class="card__table-col"><span>Цена за номер</span></div>
                                </div>
                            </div>

                            <div class="card__table-body">
                                <? foreach ($price_matrix as $month => $price) { ?>
                                    <div class="card__table-row">
                                        <div class="card__table-col"><span><?=$month?></span></div>
                                        <div class="card__table-col"><span><?=$price?> Р / сутки</span></div>
                                    </div>
                                <? } ?>
                            </div>
                        </div>
                    </div>

                    <div class="card__form">
                        <div class="card__form-open">
                            <button type="button" class="button card__form-open-button js-form-open">
                                <span class="button__text">Забронировать</span>
                            </button>
                        </div>
                        <form class="form js-form">
                            <div class="form__head">
                                <div class="form__title">Забронируйте этот номер</div>
                                <div class="form__subtitle">и наши специалисты свяжутся с вами</div>
                            </div>

                            <div class="form__items">
                                <div class="form__item">
                                    <input required="" id="form_name" name="name" placeholder="Имя" type="text" class="input form__input">
                                </div>
                                <div class="form__item">
                                    <input required="" id="form_infdata" class="input form__input js-date"
                                           placeholder="Дата (Д.М - Д.М)" type="text">
                                </div>
                                <div class="form__item">
                                    <input required="" id="form_phone" placeholder="Телефон или e-mail" type="text"
                                           class="input form__input">
                                </div>
                                <div class="form__item">


                                    <div class="counter counter--inline form__counter js-ipnut-spinner">

                                        <div class="counter__header">Количество отдыхающих</div>


                                        <div class="counter__content">
                                            <div class="counter__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="counter__reservation">
                                                <div class="counter__selected"></div>
                                                <button type="button" class="counter__change js-counter-change">Изменить</button>
                                            </div>
                                            <div class="counter__controls">
                                                <button type="button"
                                                        class="counter__button counter__button--minus js-input-spinner-minus">
                                                    <span class="counter__button-text">-</span>
                                                </button>
                                                <input value="" id="form_persons" required="" data-maxlength="2" type="number"
                                                       class="counter__input js-input-spinner-counter">
                                                <button type="button" class="counter__button counter__button--plus js-input-spinner-plus">
                                                    <span class="counter__button-text">+</span>
                                                </button>
                                            </div>
                                        </div>
                                    </div><!-- counter -->
                                </div>
                                <div class="form__item">
                                    <textarea id="form_message" placeholder="Комментарий" class="textarea form__textarea"></textarea>
                                </div>
                            </div>

                            <div class="form__button">
                                <button type="submit" class="button form__submit js-form-submit">
                                    <span class="button__text">Оставить заявку</span>
                                </button><!-- b:button -->
                            </div>

                            <div class="form__note">
                                Нажимая на кнопку, вы даете согласие на обработку своих <br>персональных данных и
                                соглашаетесь с

                                <!-- todo add pop-up policy -->
                                <a href="#">политикой <br>конфиденциальности</a>
                            </div>
                        </form><!-- form -->

                        <div class="form-thanks js-form-thanks">
                            <div class="form-thanks__image">
                                <img src="/img/form-thanks.svg" alt="">
                            </div>
                            <div class="form-thanks__title">Спасибо, что выбрали нас</div>
                            <div class="form-thanks__subtitle">Наши специалисты свяжутся с вами <br>в течение 1 часа
                            </div>
                        </div><!-- b:form-thanks -->
                    </div>
                </div>

                <div class="card__left">
                    <!-- noindex -->
                    <div class="card__images js-card-images" <?= $img_count > 0 ? '' : 'hidden' ?>>
                        <div class="card__images-counter">
                            <span class="card__images-counter-current js-card-current-slide"><?= $img_count > 0 ? 1 : 0 ?></span>
                            <span class="card__images-counter-sep">из</span>
                            <span class="card__images-counter-all"><?= $img_count ?></span>
                        </div>
                        <div class="card__images-gallery js-card-images-gallery">
                            <?
                            if($img_count > 0) { // fixme dublicate code?
                                foreach ($apart_images as $k => $image) {
                                    ?>
                                    <picture class="card__image">
                                        <source srcset="<?= $image ?>" media="(max-width: 979px)" type="image/png">
                                        <source srcset="<?= $image ?>" media="(min-width: 980px)" type="image/png">
                                        <img       src="<?= $image ?>" alt="">
                                    </picture>
                                    <?
                                }
                            }
                            ?>
                        </div>
                    </div>
                    <!-- /noindex -->
                    <div class="card__description">
                        <div class="card__text">
                            <div class="card__text-header">Описание:</div>
                            <div class="card__text-body">
                                <?= $description ?>
                            </div>
                        </div>
                        <div class="card__meta">
                            <div class="card__meta-item">
                                <strong>Комнат:</strong> <?= $rooms_count ?>
                            </div>
                            <div class="card__meta-item">
                                <strong>Кухня:</strong> <?= $kitchen ?>
                            </div>
                            <div class="card__meta-item">
                                <strong>Санузел:</strong> <?= $bathroom ?>
                            </div>
                            <div class="card__meta-item">
                                <strong>Мебель:</strong> <?= $furniture ?>
                            </div>
                            <div class="card__meta-item">
                                <strong>Этаж:</strong> <?= $floor ?>
                            </div>
                        </div>

                        <div class="contacts contacts--card">
                            <div class="contacts__header">Наши контакты:</div>
                            <div class="contacts__items">
                                <div class="contacts__item">
                                    <div class="contacts__item-content">

                                        <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#phone-icon"></use>
                                            </svg>
                                        </div>


                                        <div class="contacts__item-text">
                                            <?php render_phones(); ?>
                                        </div>
                                    </div>
                                </div>

                                <div class="contacts__item">
                                    <div class="contacts__item-content">

                                        <div class="svg-icon svg-icon--envelope" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#envelope"></use>
                                            </svg>
                                        </div>


                                        <div class="contacts__item-text">
                                            <div class="contacts__item-link">
                                                <a href="mailto:<?= config('contact_email') ?>"><?= config('contact_email') ?></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="contacts__item">
                                    <div class="contacts__item-content">

                                        <div class="svg-icon svg-icon--whatsapp" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#whatsapp"></use>
                                            </svg>
                                        </div>

                                        <div class="contacts__item-text">
                                            <div class="contacts__item-link">
                                                <a href="<?= config('social_whatsapp_link'); ?>">
                                                    <?= config('display_phones')['phone_main']; ?>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- contacts -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- card -->


<div class="apartments apartments--similar">

    <div class="apartments__headline container">
        <div class="apartments__header">Посмотрите также другие номера</div>


    </div>


    <div class="apartments__body">
        <div class="apartments__body-inside">
            <div class="apartments__body-container">
                <div class="apartments__items">

                    <div class="apartments__item">


                        <div class="apartment apartment--similar js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом</div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                    <div class="apartments__item">


                        <div class="apartment apartment--similar js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом</div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                    <div class="apartments__item">


                        <div class="apartment apartment--similar js-apartment">
                            <div class="apartment__images">


                                <div class="apartment-places apartment__places apartment__places--desktop">
                                    <div class="apartment-places__icon">

                                        <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                            <svg class="svg-icon__link">
                                                <use xlink:href="#counter-icon"></use>
                                            </svg>
                                        </div>

                                    </div>
                                    <div class="apartment-places__count">1-2</div>
                                </div>
                                <div class="apartment__images-counter">
                                    <span class="apartment__images-counter-current js-apartment-current-slide">1</span>
                                    <span class="apartment__images-counter-sep">из</span>
                                    <span class="apartment__images-counter-all">5</span>
                                </div>
                                <div class="apartment__images-gallery js-apartment-images">

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                    <picture class="apartment__image">
                                        <source srcset="/img/apartment-image@960.png" media="(max-width: 979px)"
                                                type="image/png">

                                        <source srcset="/img/apartment-image.png" media="(min-width: 980px)"
                                                type="image/png">
                                        <img src="/img/apartment-image.png" alt="">

                                    </picture>

                                </div>
                            </div>
                            <div class="apartment__body">
                                <div class="apartment__body-head">
                                    <div class="apartment__title">
                                        <div class="apartment__title-text">Двухместный номер с балконом</div>


                                        <div class="apartment-places apartment__places apartment__places--mobile">
                                            <div class="apartment-places__icon">

                                                <div class="svg-icon svg-icon--counter-icon" aria-hidden="true">
                                                    <svg class="svg-icon__link">
                                                        <use xlink:href="#counter-icon"></use>
                                                    </svg>
                                                </div>

                                            </div>
                                            <div class="apartment-places__count">1-2</div>
                                        </div>
                                    </div>
                                    <div class="apartment__price">1500-2000 Р/сутки</div>
                                </div>

                                <div class="apartment__body-hidden">
                                    <div class="apartment__body-limit">
                                        <div class="apartment__adds">

                                            <div class="svg-icon svg-icon--check svg-icon--colored" aria-hidden="true">
                                                <svg class="svg-icon__link">
                                                    <use xlink:href="#check"></use>
                                                </svg>
                                            </div>

                                            Бесплатная автостоянка, Wi-Fi, спутниковое TV, xолодильник, душ,
                                            кондиционер, кухня, сейф
                                        </div>
                                        <div class="apartment__columns">
                                            <div class="apartment__column apartment__column--more">
                                                <a href="#" class="apartment__more">
                                                    <span class="apartment__more-text">Подробнее</span>
                                                    <span class="apartment__more-icon">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                            </span>
                                                </a>
                                            </div>
                                            <div class="apartment__column apartment__column--price">
                                                <div class="apartment__price">
                                                    <div class="apartment__price-num">1500-2000 Р</div>
                                                    <div class="apartment__price-adds">за номер в сутки</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="apartment__order">
                                    <a href="#1" class="button apartment__order-button">
                                        <span class="button__text">Забронировать</span>
                                    </a><!-- b:button -->
                                </div>
                            </div>
                        </div><!-- apartment -->
                    </div>

                </div>
            </div>
        </div>
    </div>


</div><!-- apartments -->
