<div class="reviews">
    <div class="reviews__container container">
        <div class="reviews__header">Отзывы</div>

        <div class="reviews__items js-reviews-slider">

            <div class="reviews__item">
                <div class="reviews__name">Анастасия</div>
                <div class="reviews__text">«Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor
                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                    exercitation ullamco
                    laboris nis»
                </div>
                <div class="rating reviews__rating js-rating" data-value="100%">
                    <div class="rating__stars">
                        <div class="rating__stars-fill js-rating-fill"></div>
                    </div>
                </div><!-- rating -->
            </div>

            <div class="reviews__item">
                <div class="reviews__name">Петр</div>
                <div class="reviews__text">«Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor
                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                    exercitation ullamco
                    laboris nis»
                </div>
                <div class="rating reviews__rating js-rating" data-value="90%">
                    <div class="rating__stars">
                        <div class="rating__stars-fill js-rating-fill"></div>
                    </div>
                </div><!-- rating -->
            </div>

            <div class="reviews__item">
                <div class="reviews__name">Василий</div>
                <div class="reviews__text">«Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                    eiusmod tempor
                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                    exercitation ullamco
                    laboris nis»
                </div>
                <div class="rating reviews__rating js-rating" data-value="80%">
                    <div class="rating__stars">
                        <div class="rating__stars-fill js-rating-fill"></div>
                    </div>
                </div><!-- rating -->
            </div>

        </div>

        <div class="reviews__counter">
            <div class="reviews__counter-current js-reviews-slider-current">1</div>
            <div class="reviews__counter-sep">/</div>
            <div class="reviews__counter-all">3</div>
        </div>
    </div>
</div><!-- reviews -->