<div class="hero hero--inside">
    <div class="hero__bg js-app-bg" data-bg="img/hero-pick-up-bg.png"></div>

    <div class="hero__content">
        <div class="hero__text">

            <h1 class="hero__header h1">Контакты</h1>


            <nav class="crumbs">
                <div class="crumbs__items">

                    <div class="crumbs__item">

                        <a href="index.html" class="crumbs__link">Главная</a>
                        <span class="crumbs__sep">

      <span class="svg-icon svg-icon--arrorw-right" aria-hidden="true">
        <svg class="svg-icon__link">
          <use xlink:href="#arrorw-right"></use>
        </svg>
      </span>

                    </span>

                    </div>

                    <div class="crumbs__item">

                        <span href="contacts.html" class="crumbs__current">Контакты</span>

                    </div>

                </div>
            </nav><!-- crumbs -->

        </div>
    </div>
</div><!-- hero -->


<div class="contacts">
    <div class="contacts__container container">
        <div class="contacts__content">
            <p>При бронировании мы попросим Вас отправить нам предоплату в сумме одних суток аренды вашего номера на
                карту Сбербанка</p>
            <p>Расчетный час в наших апартаментах – <strong>10:00</strong></p>
            <div class="contacts__items">
                <div class="contacts__items-header">
                    <div class="contacts__item">
                        <div class="contacts__item-header">Адрес:</div>
                        <div class="contacts__item-content">

                            <div class="svg-icon svg-icon--flag" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#flag"></use>
                                </svg>
                            </div>


                            <div class="contacts__item-text">Краснодарский край, Геленджикский район, п. Бетта, ул.
                                Садовая,
                                д.4Б
                            </div>
                        </div>
                    </div>

                    <div class="contacts__item">
                        <div class="contacts__item-header">Телефоны:</div>
                        <div class="contacts__item-content">

                            <div class="svg-icon svg-icon--phone-icon" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#phone-icon"></use>
                                </svg>
                            </div>


                            <div class="contacts__item-text">
                                <div class="contacts__item-link">
                                    <a href="tel:">8 (960) 489 60 93 (Наталья)</a>
                                </div>
                                <div class="contacts__item-link">
                                    <a href="tel:">8 (988) 954 20 97</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="contacts__items-footer">
                    <div class="contacts__item">
                        <div class="contacts__item-content">

                            <div class="svg-icon svg-icon--envelope" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#envelope"></use>
                                </svg>
                            </div>


                            <div class="contacts__item-text">
                                <div class="contacts__item-link">
                                    <a href="mailto:admin@resort-betta.ru">admin@resort-betta.ru</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="contacts__item">
                        <div class="contacts__item-content">

                            <div class="svg-icon svg-icon--skype" aria-hidden="true">
                                <svg class="svg-icon__link">
                                    <use xlink:href="#skype"></use>
                                </svg>
                            </div>


                            <div class="contacts__item-text">
                                <div class="contacts__item-link">
                                    <a href="skype:admin@resort-betta.ru">n.vakary</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="contacts__image">
            <div class="contacts__image-inside">
                <picture class="contacts__picture">
                    <source srcset="img/contacts-desktop.png" media="(max-width: 979px)" type="image/png">
                    <source srcset="img/contacts-desktop.png" media="(min-width: 980px)" type="image/png">
                    <img src="img/contacts-desktop.png" alt="">
                </picture>
            </div>
        </div>
    </div>
</div><!-- contacts -->